services:
  mc-discord:
    build:
      context: .
      dockerfile: Dockerfile
    image: mc-discord:local
    pull_policy: build
    container_name: mc-discord
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - minecraftserver:/data:ro
    command: ["-log", "/data/logs/latest.log"]

volumes:
  minecraftserver:
    external: true
    name: minecraftserverwithvps_minecraftserver #Replace this with what is needed.
